# Generated by Django 4.2.11 on 2026-01-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='role',
        ),
        migrations.AddField(
            model_name='resume',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
